name: Nano_NVDevKitB01_L4T32.5.2

on:
  push:
    branches: [ action_test ]
  pull_request:
    branches: [ action_test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure the driver
      run: cd bin && ./config/setup.sh -s 1 -b 1 -p 3 -d 
    - name: Setup the kernel sources
      run: cd bin && ./setup.sh -k
